'use strict';

Rpg.tiles = {
    "iii": {
        name: "Grass",
        position: 0,
        moveRate: 1,
        damageRate: 0,
    },
    "SIG": {
        name: "Signpost",
        position: 1,
        moveRate: 0,
        damageRate: 0,
    },
    "sss": {
        name: "Scrub",
        position: 2,
        moveRate: 1,
        damageRate: 0,
    },
    "fff": {
        name: "Trees (outdoor)",
        position: 3,
        moveRate: .9,
        damageRate: 0,
    },
    "mmm": {
        name: "Low Mountains",
        position: 4,
        moveRate: 0.6,
        damageRate: 0,
    },
    "MMM": {
        name: "High Mountains",
        position: 5,
        moveRate: 0,
        damageRate: 0,
    },
    "TWN": {
        name: "Town / Village",
        position: 6,
        moveRate: 1,
        damageRate: 0,
    },
    "xxx": {
        name: "Swamp",
        position: 7,
        moveRate: .8,
        damageRate: 0,
    },
    "ddd": {
        name: "Desert",
        position: 8,
        moveRate: 1,
        damageRate: 0,
    },
    "___": {
        name: "Ocean",
        position: 9,
        moveRate: 0,
        damageRate: 0,
    },
    "__t": {
        name: "Ocean Top shore",
        position: 10,
        moveRate: 0,
        damageRate: 0,
    },
    "__r": {
        name: "Ocean Right shore",
        position: 11,
        moveRate: 0,
        damageRate: 0,
    },
    "__b": {
        name: "Ocean Bottom shore",
        position: 12,
        moveRate: 0,
        damageRate: 0,
    },
    "__l": {
        name: "Ocean Left shore",
        position: 13,
        moveRate: 0,
        damageRate: 0,
    },
    "_tr": {
        name: "Ocean Top Right shore",
        position: 14,
        moveRate: 0,
        damageRate: 0,
    },
    "_tl": {
        name: "Ocean Top Left shore",
        position: 15,
        moveRate: 0,
        damageRate: 0,
    },
    "_rb": {
        name: "Ocean Right Bottom shore",
        position: 16,
        moveRate: 0,
        damageRate: 0,
    },
    "_bl": {
        name: "Ocean Left Bottom shore",
        position: 17,
        moveRate: 0,
        damageRate: 0,
    },
    "_rl": {
        name: "Ocean Left Right shore",
        position: 18,
        moveRate: 0,
        damageRate: 0,
    },
    "_tb": {
        name: "Ocean: Top Bottom shore",
        position: 19,
        moveRate: 0,
        damageRate: 0,
    },
    "tbl": {
        name: "Ocean: top bottom left shore",
        position: 20,
        moveRate: 0,
        damageRate: 0,
    },
    "rbl": {
        name: "Ocean: right bottom left shore",
        position: 21,
        moveRate: 0,
        damageRate: 0,
    },
    "trl": {
        name: "Ocean: left top right",
        position: 22,
        moveRate: 0,
        damageRate: 0,
    },
    "trb": {
        name: "Ocean: top, right, bottom, shores",
        position: 23,
        moveRate: 0,
        damageRate: 0,
    },
    "BBR": {
        name: "Bridge - Broken",
        position: 24,
        moveRate: 0,
        damageRate: 0,
    },
    "BRG": {
        name: "Bridge",
        position: 25,
        moveRate: 1,
        damageRate: 0,
    },
    "TWT": {
        name: "Tower Top",
        position: 26,
        moveRate: 1,
        damageRate: 0,
    },
    "TOW": {
        name: "Tower Bottom",
        position: 27,
        moveRate: 1,
        damageRate: 0,
    },
    "CVE": {
        name: "Small Cave",
        position: 28,
        moveRate: 1,
        damageRate: 0,
    },
    "CVL": {
        name: "Cave - left",
        position: 29,
        moveRate: 1,
        damageRate: 0,
    },
    "CVR": {
        name: "Cave - right",
        position: 30,
        moveRate: 1,
        damageRate: 0,
    },

    "CNW": {
        name: "Castle - north west",
        position: 31,
        moveRate: 1,
        damageRate: 0,
    },
    "CNE": {
        name: "Castle - north east",
        position: 32,
        moveRate: 1,
        damageRate: 0,
    },
    "CSW": {
        name: "Castle - south west",
        position: 33,
        moveRate: 1,
        damageRate: 0,
    },
    "CSE": {
        name: "Castle - south east",
        position: 34,
        moveRate: 1,
        damageRate: 0,
    },
    "FFF": {
        name: "Tree (indoor)",
        position: 35,
        moveRate: 1,
        damageRate: 0,
    },
    "QQQ": {
        name: "Flowers (indoor)",
        position: 36,
        moveRate: 1,
        damageRate: 0,
    },

    "bbb": {
        name: "Bricks / Road",
        position: 37,
        moveRate: 1,
        damageRate: 0,
    },
    "www": {
        name: "Water: town",
        position: 38,
        moveRate: 0,
        damageRate: 0,
    },

    "DSK": {
        name: "Desk",
        position: 41,
        moveRate: 0,
        damageRate: 0,
    },
    "INN": {
        name: "Sign: Inn",
        position: 42,
        moveRate: 0,
        damageRate: 0,
    },
    "WPN": {
        name: "Sign: Weapon seller",
        position: 46,
        moveRate: 0,
        damageRate: 0,
    },
    "TRS": {
        name: "Treasure Chest",
        position: 47,
        moveRate: 1,
        damageRate: 0,
    },
    "DR1": {
        name: "Door: style 1",
        position: 48,
        moveRate: 0,
        damageRate: 0,
    },

    "TTT": {
        name: "Wall top",
        position: 52,
        moveRate: 0,
        damageRate: 0,
    },
    "HHH": {
        name: "Wall back",
        position: 53,
        moveRate: 0,
        damageRate: 0,
    },
    "rrr": {
        name: "Roof",
        position: 54,
        moveRate: 0,
        damageRate: 0,
    },
    "STD": {
        name: "Stair: down",
        position: 55,
        moveRate: 1,
        damageRate: 0,
    },
    "STU": {
        name: "Stair: up",
        position: 56,
        moveRate: 1,
        damageRate: 0,
    },
    // FLOOR THINGS
    "ooo": {
        name: "Floor",
        position: 57,
        moveRate: 1,
        damageRate: 0,
    },
    "oxo": {
        name: "Floor: broken",
        position: 58,
        moveRate: 1,
        damageRate: 0,
    },
    "oPo": {
        name: "Floor: Pillar",
        position: 59,
        moveRate: 1,
        damageRate: 0,
    },
    "oCo": {
        name: "Floor: Chair",
        position: 60,
        moveRate: 1,
        damageRate: 0,
    },
    "oTo": {
        name: "Floor: Table",
        position: 61,
        moveRate: 0,
        damageRate: 0,
    },
    "ooB": {
        name: "Floor: Bed - left",
        position: 62,
        moveRate: 0,
        damageRate: 0,
    },
    "Boo": {
        name: "Floor: Bed - right",
        position: 63,
        moveRate: 0,
        damageRate: 0,
    },

    "DRW": {
        name: "Drawers",
        position: 66,
        moveRate: 1,
        damageRate: 0,
    },
    "THC": {
        name: "Throne: carpet",
        position: 69,
        moveRate: 1,
        damageRate: 0,
    },
    "THB": {
        name: "Throne: back",
        position: 70,
        moveRate: 0,
        damageRate: 0,
    },
    "THR": {
        name: "Throne: right",
        position: 71,
        moveRate: 0,
        damageRate: 0,
    },
    "THL": {
        name: "Throne: left",
        position: 72,
        moveRate: 0,
        damageRate: 0,
    },
    "THA": {
        name: "Throne: arm",
        position: 73,
        moveRate: 1,
        damageRate: 0,
    },

    "BAR": {
        name: "Barrier",
        position: 76,
        moveRate: 1,
        damageRate: 0,
    },
    "WEL": {
        name: "Well",
        position: 77,
        moveRate: 0,
        damageRate: 0,
    },

    "BLACKOUT": {
        name: "Blackout",
        position: 84,
        moveRate: 1,
        damageRate: 0,
    },
};
